local test = T.test

local function slash(t, msg)
  t.W.clearChat()
  SlashCmdList.THREATDIFF(msg)
  return t.W.chatText()
end

test("slash: /tdiff and /threatdiff are both registered", function(t)
  t:boot()
  t.eq(_G.SLASH_THREATDIFF1, "/tdiff")
  t.eq(_G.SLASH_THREATDIFF2, "/threatdiff")
  t.ok(SlashCmdList.THREATDIFF)
end)

test("slash: bare /tdiff, config and options open the settings window", function(t)
  local W, TD = t:boot()
  slash(t, "")
  t.ok(_G.ThreatDiffConfig and _G.ThreatDiffConfig:IsShown(), "window should open")
  slash(t, "")
  t.eq(_G.ThreatDiffConfig:IsShown(), false, "second call closes it")
  slash(t, "config"); t.eq(_G.ThreatDiffConfig:IsShown(), true)
  slash(t, "options"); t.eq(_G.ThreatDiffConfig:IsShown(), false)
end)

test("slash: pos prints, sets both axes, accepts every documented spelling", function(t)
  local W, TD = t:boot()
  t.has(slash(t, "pos"), "x %-6%.00, y 0%.00")
  slash(t, "pos 2.34 10.25");            t.eq(TD.db.x, 2.34); t.eq(TD.db.y, 10.25)
  slash(t, "pos 1.5, -3");               t.eq(TD.db.x, 1.5);  t.eq(TD.db.y, -3)
  slash(t, "pos x, 4.5 y, -7.25");       t.eq(TD.db.x, 4.5);  t.eq(TD.db.y, -7.25)
  slash(t, "pos x 8 y 9");               t.eq(TD.db.x, 8);    t.eq(TD.db.y, 9)
  slash(t, "pos y=2");                   t.eq(TD.db.x, 8);    t.eq(TD.db.y, 2)
  slash(t, "pos x=-0.5");                t.eq(TD.db.x, -0.5); t.eq(TD.db.y, 2)
  slash(t, "pos 7");                     t.eq(TD.db.x, 7);    t.eq(TD.db.y, 2)
  slash(t, "pos 1.005 2.345");           t.eq(TD.db.x, 1.01); t.eq(TD.db.y, 2.35)
  slash(t, "POS 3 4");                   t.eq(TD.db.x, 3);    t.eq(TD.db.y, 4)
  slash(t, "xy 5 6");                    t.eq(TD.db.x, 5);    t.eq(TD.db.y, 6)
  slash(t, "position 9 9");              t.eq(TD.db.x, 9)
end)

test("slash: pos rejects garbage with a hint and keeps the old value", function(t)
  local W, TD = t:boot()
  local out = slash(t, "pos banana")
  t.has(out, "couldn't read that")
  t.eq(TD.db.x, -6)
end)

test("slash: x / y set a single axis", function(t)
  local W, TD = t:boot()
  slash(t, "x 2.34"); t.eq(TD.db.x, 2.34); t.eq(TD.db.y, 0)
  slash(t, "y 10.25"); t.eq(TD.db.y, 10.25); t.eq(TD.db.x, 2.34)
  slash(t, "y -4"); t.eq(TD.db.y, -4)
  t.has(slash(t, "x"), "usage")
  t.has(slash(t, "y abc"), "usage")
end)

test("slash: point sets anchors, validates names", function(t)
  local W, TD = t:boot()
  slash(t, "point TOP BOTTOM")
  t.eq(TD.db.point, "TOP"); t.eq(TD.db.relPoint, "BOTTOM")
  slash(t, "point left")
  t.eq(TD.db.point, "LEFT"); t.eq(TD.db.relPoint, "BOTTOM", "second arg optional")
  t.has(slash(t, "point NOWHERE"), "points:")
  t.eq(TD.db.point, "LEFT")
  t.has(slash(t, "point TOP NOWHERE"), "points:")
  slash(t, "anchor RIGHT LEFT"); t.eq(TD.db.point, "RIGHT")
end)

test("slash: edit opens and closes the position editor", function(t)
  local W, TD = t:boot()
  slash(t, "edit")
  t.ok(_G.ThreatDiffEditor and _G.ThreatDiffEditor:IsShown())
  slash(t, "edit"); t.eq(_G.ThreatDiffEditor:IsShown(), false)
  slash(t, "move"); t.eq(_G.ThreatDiffEditor:IsShown(), true)
end)

test("slash: test toggles sample numbers", function(t)
  local W, TD = t:boot()
  local mob = t:engage("nameplate1")
  t.has(slash(t, "test"), "test mode ON")
  t.eq(TD.testMode, true); t.eq(t:plate().vis, true)
  t.has(slash(t, "test"), "test mode off")
  t.eq(TD.testMode, false); t.eq(t:plate().vis, false)
end)

test("slash: role validates and reports", function(t)
  local W, TD = t:boot()
  t.has(slash(t, "role tank"), "Tank"); t.eq(TD.db.role, "TANK")
  t.has(slash(t, "role dps"), "DPS"); t.eq(TD.db.role, "DPS")
  slash(t, "role healer"); t.eq(TD.db.role, "DPS")
  slash(t, "role heal"); t.eq(TD.db.role, "DPS")
  t.has(slash(t, "role auto"), "Auto"); t.eq(TD.db.role, "AUTO")
  t.has(slash(t, "role wizard"), "usage"); t.eq(TD.db.role, "AUTO")
  t.has(slash(t, "role"), "usage")
end)

test("slash: on / off / toggle", function(t)
  local W, TD = t:boot()
  t.has(slash(t, "off"), "disabled"); t.eq(TD.db.enabled, false)
  t.has(slash(t, "on"), "enabled"); t.eq(TD.db.enabled, true)
  slash(t, "toggle"); t.eq(TD.db.enabled, false)
  slash(t, "toggle"); t.eq(TD.db.enabled, true)
end)

test("slash: stats prints live cost", function(t)
  local W, TD = t:boot()
  local out = slash(t, "stats")
  t.has(out, "plates showing")
  t.has(out, "threat calls/s")
  t.has(out, "123%.4 KB", "memory read through C_AddOns on the modern API")
end)

test("slash: stats also works when the legacy memory globals exist", function(t)
  local W, TD = t:boot()
  _G.UpdateAddOnMemoryUsage = function() end
  _G.GetAddOnMemoryUsage = function() return 77 end
  t.has(slash(t, "stats"), "77%.0 KB")
end)

test("slash: probe arms out of combat, reports in combat", function(t)
  local W, TD = t:boot()
  local mob = t:engage("nameplate1", "Boar", true)
  t:set(mob, W.player, 5000, { tank = true })
  t.has(slash(t, "probe"), "probe armed")
  t.eq(TD.probeArmed, true)
  W.enterCombat(); W.advance(3.1)
  local out = W.chatText()
  t.has(out, "probe %- in combat")
  t.has(out, "target")
  t.has(out, "routes:")
  t.eq(TD.probeArmed, false)
  -- in-combat call reports immediately; secret values are flagged
  W.hideOnPlates = true
  W.clearChat()
  SlashCmdList.THREATDIFF("debug")
  t.has(W.chatText(), "SECRET")
  t.has(W.chatText(), "enemy plates")
end)

test("slash: probe with nothing targeted says so", function(t)
  local W, TD = t:boot()
  W.enterCombat()
  t.has(slash(t, "probe"), "no target")
end)

test("slash: minimap toggles the button", function(t)
  local W, TD = t:boot()
  t.has(slash(t, "minimap"), "hidden")
  t.eq(_G.ThreatDiffMinimapButton:IsShown(), false)
  t.has(slash(t, "minimap"), "shown")
  t.eq(_G.ThreatDiffMinimapButton:IsShown(), true)
end)

test("slash: meter lock / unlock / collapse / expand / reset", function(t)
  local W, TD = t:boot()
  slash(t, "meter lock");    t.eq(TD.db.meter.locked, true)
  slash(t, "meter unlock");  t.eq(TD.db.meter.locked, false)
  slash(t, "meter collapse"); t.eq(TD.db.meter.collapsed, true)
  slash(t, "meter collapse"); t.eq(TD.db.meter.collapsed, false, "collapse toggles")
  slash(t, "meter collapse"); slash(t, "meter expand"); t.eq(TD.db.meter.collapsed, false)
  TD.db.meter.x, TD.db.meter.y = 1, 2
  slash(t, "meter reset")
  t.eq(TD.db.meter.x, TD.DEFAULTS.meter.x); t.eq(TD.db.meter.y, TD.DEFAULTS.meter.y)
  t.has(slash(t, "meter nonsense"), "usage")
end)

test("slash: meter show / hide / toggle", function(t)
  local W, TD = t:boot()
  slash(t, "meter hide"); t.eq(TD.db.meter.enabled, false); t.eq(_G.ThreatDiffMeter:IsShown(), false)
  slash(t, "meter show"); t.eq(TD.db.meter.enabled, true);  t.eq(_G.ThreatDiffMeter:IsShown(), true)
  slash(t, "meter toggle"); t.eq(TD.db.meter.enabled, false)
  slash(t, "meter toggle"); t.eq(TD.db.meter.enabled, true)
end)

test("slash: bare '/tdiff meter' shows/hides the meter (as the in-game help says)", function(t)
  -- HELP: "/tdiff meter - show/hide the threat meter". Press it twice: it should hide again.
  local W, TD = t:boot()
  t.eq(TD.db.meter.enabled, true)
  slash(t, "meter")
  t.eq(TD.db.meter.enabled, false, "first /tdiff meter should hide a visible meter")
  slash(t, "meter")
  t.eq(TD.db.meter.enabled, true, "second /tdiff meter should show it again")
end)

test("slash: reset puts the profile back to defaults", function(t)
  local W, TD = t:boot()
  slash(t, "pos 9 9"); slash(t, "role tank")
  t.has(slash(t, "reset"), "reset to defaults")
  t.eq(TD.db.x, -6); t.eq(TD.db.role, "AUTO")
end)

test("slash: help and unknown commands list every command", function(t)
  local W, TD = t:boot()
  local out = slash(t, "help")
  for _, c in ipairs({ "/tdiff pos", "/tdiff edit", "/tdiff test", "/tdiff role", "/tdiff meter", "/tdiff profile",
    "/tdiff minimap", "/tdiff stats", "/tdiff probe", "/tdiff reset" }) do
    t.has(out, c:gsub("%p", "%%%0"), "help is missing " .. c)
  end
  t.has(slash(t, "frobnicate"), "/tdiff pos")
end)

test("slash: ParseXY handles each README form", function(t)
  local W, TD = t:boot()
  local function xy(s) local x, y = TD.ParseXY(s); return x, y end
  local x, y = xy("2.34 10.25"); t.eq(x, 2.34); t.eq(y, 10.25)
  x, y = xy("x, 2.34 y, 10.25"); t.eq(x, 2.34); t.eq(y, 10.25)
  x, y = xy("-6 0"); t.eq(x, -6); t.eq(y, 0)
  x, y = xy("+3 -2"); t.eq(x, 3); t.eq(y, -2)
  x, y = xy(".5 .25"); t.eq(x, 0.5); t.eq(y, 0.25)
  x, y = xy("nothing"); t.eq(x, nil); t.eq(y, nil)
end)
