local test = T.test

local function slash(t, msg)
  t.W.clearChat()
  SlashCmdList.THREATDIFF(msg)
  return t.W.chatText()
end

test("profiles: fresh install creates Default with all defaults", function(t)
  local W, TD = t:boot()
  t.eq(TD.profileName, "Default")
  t.eq(TD.db.x, -6); t.eq(TD.db.meter.width, 260); t.eq(TD.db.colors.SECURE[2], 1)
  t.eq(_G.ThreatDiffDB.chars["Tester - Testrealm"], "Default")
  t.eq(_G.ThreatDiffDB.version, 2)
  t.ok(_G.ThreatDiffDB.minimap and _G.ThreatDiffDB.minimap.hide == false)
end)

test("profiles: an old flat save is moved into Default without losing values", function(t)
  local W, TD = t:boot({ saved = { x = 5, y = 3, enabled = false, role = "TANK",
    meter = { width = 333 }, colors = { SECURE = { 0.1, 0.2, 0.3 } }, saved = true } })
  t.eq(TD.profileName, "Default")
  t.eq(TD.db.x, 5); t.eq(TD.db.y, 3); t.eq(TD.db.enabled, false); t.eq(TD.db.role, "TANK")
  t.eq(TD.db.meter.width, 333); t.eq(TD.db.meter.height, 214, "new keys are filled from defaults")
  t.eq(TD.db.colors.SECURE[1], 0.1)
  t.eq(TD.db.colors.TANKING[1], 1, "missing colours are filled in")
  t.eq(_G.ThreatDiffDB.x, nil, "old flat keys removed from the root")
  t.eq(_G.ThreatDiffDB.profiles.Default.saved, nil)
end)

test("profiles: a save from the row-count meter era keeps its size as a fixed height", function(t)
  local W, TD = t:boot({ saved = { profiles = { Default = { meter = { maxBars = 5, barHeight = 18, spacing = 1 } } }, chars = {} } })
  t.eq(TD.db.meter.height, TD.MeterHeightFor(5, 18, 1))
  t.eq(TD.MeterRowsFit(), 5)
end)

test("profiles: corrupt saved data does not stop the addon loading", function(t)
  local W, TD = t:boot({ saved = { profiles = { Default = { meter = "x", colors = 4, x = "wide" } }, chars = { ["Tester - Testrealm"] = "Missing" }, minimap = 3 } })
  t.eq(type(TD.db.meter), "table")
  t.eq(type(TD.db.colors), "table")
  t.eq(TD.profileName, "Default", "falls back to Default when the remembered profile is gone")
end)

test("profiles: garbage root values are replaced", function(t)
  local W, TD = t:boot({ saved = "junk" })
  t.eq(TD.profileName, "Default")
  t.eq(type(_G.ThreatDiffDB), "table")
end)

test("profiles: each character remembers its own profile", function(t)
  local W, TD = t:boot({ saved = { profiles = { Default = {}, Raid = { x = 12 } },
    chars = { ["Tester - Testrealm"] = "Raid", ["Other - Testrealm"] = "Default" } } })
  t.eq(TD.profileName, "Raid"); t.eq(TD.db.x, 12)
  t.eq(_G.ThreatDiffDB.chars["Other - Testrealm"], "Default")
end)

test("profiles: new / switch / duplicate keep settings independent", function(t)
  local W, TD = t:boot()
  TD.db.x = 7
  t.ok(TD:NewProfile("Tank"))
  t.eq(TD.profileName, "Tank"); t.eq(TD.db.x, -6, "new profile starts from defaults")
  TD.db.x = 1
  t.ok(TD:NewProfile("Tank copy", "Default"))
  t.eq(TD.db.x, 7, "copy of Default")
  t.ok(TD:SetProfile("tank"), "case-insensitive switch")
  t.eq(TD.profileName, "Tank"); t.eq(TD.db.x, 1)
  t.eq(_G.ThreatDiffDB.chars["Tester - Testrealm"], "Tank")
  local list = TD:GetProfiles()
  t.eq(list[1], "Default"); t.eq(#list, 3)
end)

test("profiles: name validation", function(t)
  local W, TD = t:boot()
  local ok, err = TD:NewProfile("   "); t.eq(ok, false); t.has(err, "1%-40")
  ok, err = TD:NewProfile(string.rep("x", 41)); t.eq(ok, false)
  ok, err = TD:NewProfile("Default"); t.eq(ok, false); t.has(err, "already exists")
  ok, err = TD:NewProfile("DEFAULT"); t.eq(ok, false, "names are not case sensitive")
  ok = TD:NewProfile("  Padded  "); t.eq(ok, true); t.eq(TD.profileName, "Padded", "whitespace trimmed")
  ok, err = TD:SetProfile("nope"); t.eq(ok, false); t.has(err, "no profile")
end)

test("profiles: rename moves characters over; Default cannot be renamed", function(t)
  local W, TD = t:boot()
  TD:NewProfile("Raid")
  TD.db.x = 4
  t.ok(TD:RenameProfile("Raid", "Raids"))
  t.eq(TD.profileName, "Raids"); t.eq(TD.db.x, 4)
  t.eq(_G.ThreatDiffDB.chars["Tester - Testrealm"], "Raids")
  t.eq(_G.ThreatDiffDB.profiles.Raid, nil)
  local ok, err = TD:RenameProfile("Default", "X"); t.eq(ok, false); t.has(err, "can't be renamed")
  TD:NewProfile("Other")
  ok, err = TD:RenameProfile("Other", "raids"); t.eq(ok, false); t.has(err, "already exists")
  t.ok(TD:RenameProfile("Raids", "raids"), "changing only the case is allowed")
  t.ok(_G.ThreatDiffDB.profiles.raids, "renamed to lower case")
  t.eq(_G.ThreatDiffDB.profiles.Raids, nil)
end)

test("profiles: renaming to the identical name keeps the profile (the Rename box is pre-filled with the old name)", function(t)
  local W, TD = t:boot()
  TD:NewProfile("Raid"); TD.db.x = 4
  t.ok(TD:RenameProfile("Raid", "Raid"))
  t.ok(_G.ThreatDiffDB.profiles.Raid, "profile must not vanish")
  t.eq(TD.db.x, 4)
end)

test("profiles: delete rules", function(t)
  local W, TD = t:boot()
  TD:NewProfile("A"); TD:NewProfile("B")
  local ok, err = TD:DeleteProfile("B"); t.eq(ok, false); t.has(err, "switch to another")
  ok, err = TD:DeleteProfile("Default"); t.eq(ok, false); t.has(err, "can't be deleted")
  ok, err = TD:DeleteProfile("zzz"); t.eq(ok, false)
  t.ok(TD:DeleteProfile("A"))
  t.eq(_G.ThreatDiffDB.profiles.A, nil)
  t.eq(#TD:GetProfiles(), 2)
end)

test("profiles: deleting a profile another character used resets that character to Default", function(t)
  local W, TD = t:boot({ saved = { profiles = { Default = {}, Gone = {} },
    chars = { ["Alt - Testrealm"] = "Gone" } } })
  t.ok(TD:DeleteProfile("Gone"))
  t.eq(_G.ThreatDiffDB.chars["Alt - Testrealm"], nil)
end)

test("profiles: copy replaces the current profile; reset wipes it", function(t)
  local W, TD = t:boot()
  TD.db.x = 99; TD.db.colors.SECURE = { 0, 0, 0 }
  TD:NewProfile("Other"); TD.db.x = 5
  t.ok(TD:CopyProfile("Default"))
  t.eq(TD.db.x, 99); t.eq(TD.db.colors.SECURE[1], 0)
  local ok, err = TD:CopyProfile("Other"); t.eq(ok, false); t.has(err, "different profile")
  TD:ResetProfile()
  t.eq(TD.db.x, -6); t.eq(TD.db.colors.SECURE[1], 0.25)
  t.eq(_G.ThreatDiffDB.profiles.Default.x, 99, "other profiles untouched by reset")
end)

test("profiles: ProfileUsers lists characters on a profile", function(t)
  local W, TD = t:boot({ saved = { profiles = { Default = {}, Raid = {} },
    chars = { ["Zed - Testrealm"] = "Raid", ["Amy - Testrealm"] = "Raid" } } })
  local u = TD:ProfileUsers("Raid")
  t.eq(#u, 2); t.eq(u[1], "Amy - Testrealm")
end)

test("profiles: slash commands list/use/new/copy/delete/reset", function(t)
  local W, TD = t:boot()
  TD.db.x = 3
  t.has(slash(t, "profile"), "Default")
  t.has(slash(t, "profile new Raid"), "created and switched to")
  t.eq(TD.profileName, "Raid")
  t.has(slash(t, "profile new Raid"), "already exists")
  TD.db.x = 8
  t.has(slash(t, "profile use default"), "now using profile")
  t.eq(TD.profileName, "Default"); t.eq(TD.db.x, 3)
  t.has(slash(t, "profile use nope"), "no profile")
  t.has(slash(t, "profile copy raid"), "copied")
  t.eq(TD.db.x, 8)
  t.has(slash(t, "profile delete raid"), "deleted")
  t.has(slash(t, "profile delete Default"), "can't be deleted")
  t.has(slash(t, "profile reset"), "reset to defaults")
  t.eq(TD.db.x, -6)
  t.has(slash(t, "profile bogus"), "usage")
  t.has(slash(t, "profiles list"), "profiles")
  t.has(slash(t, "profile switch default"), "now using")
end)

test("profiles: switching profile re-applies colours, position and meter live", function(t)
  local W, TD = t:boot()
  local mob = t:engage("nameplate1")
  TD:NewProfile("Wide")
  TD.db.x = 40; TD.db.meter.width = 400
  TD.db.colors.SECURE = { 0, 0, 1 }
  TD:SetProfile("Default")
  t.eq(TD.active.nameplate1.fs._.points[1].x, -6)
  t.eq(_G.ThreatDiffMeter:GetWidth(), 260)
  TD:SetProfile("Wide")
  t.eq(TD.active.nameplate1.fs._.points[1].x, 40)
  t.eq(_G.ThreatDiffMeter:GetWidth(), 400)
end)
